// Single source of truth for this food truck client.
export const TRUCK_CONFIG = {
  truckId: 'demo-food-truck',
  restaurantId: 'demo-food-truck', // alias kept for createOrder/getCustomerOrders compatibility
  name: 'Demo Food Truck',
  tagline: 'Fresh food. Fast service. Your city.',
  logoText: '🚚',
  primaryColor: '#F97316',
  accentColor: '#F97316',
  accentAmber: '#FBBF24',
  bgPrimary: '#0d0d0d',
  bgSecondary: '#161616',
  bgCard: '#1c1c1c',
  textPrimary: '#FFFFFF',
  textSecondary: '#9CA3AF',
  borderSubtle: 'rgba(249, 115, 22, 0.2)',
  heroImage: 'https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?w=1600',
  address: 'San Antonio, TX (moves daily)',
  phone: '(210) 555-0200',
  email: 'hello@demofoodtruck.demo',
  instagram: '@demofoodtruck',
  hours: { Mon: '11am–3pm', Tue: '11am–3pm', Wed: 'Closed', Thu: '11am–8pm', Fri: '11am–9pm', Sat: '12pm–9pm', Sun: 'Closed' },
  schedule: {
    Mon: { location: 'Downtown Plaza',     address: '300 Main Plaza, San Antonio, TX',          hours: '11am–3pm' },
    Tue: { location: 'Tech District',      address: '1100 Broadway St, San Antonio, TX',        hours: '11am–3pm' },
    Wed: { location: 'Closed',             address: '',                                          hours: 'Closed' },
    Thu: { location: 'Pearl Brewery',      address: '303 Pearl Pkwy, San Antonio, TX',          hours: '11am–8pm' },
    Fri: { location: 'Southtown Block',    address: '1500 S Alamo St, San Antonio, TX',         hours: '11am–9pm' },
    Sat: { location: 'Brackenridge Park',  address: '3700 N St Marys St, San Antonio, TX',      hours: '12pm–9pm' },
    Sun: { location: 'Closed',             address: '',                                          hours: 'Closed' },
  },
  googleMapsUrl: 'https://maps.google.com',
  appleMapsUrl: 'https://maps.apple.com',
  galleryImages: [
    'https://images.unsplash.com/photo-1565123409695-7b5ef63a2efb?w=600',
    'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=600',
    'https://images.unsplash.com/photo-1513639776629-7b61b0ac49cb?w=600',
    'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600',
    'https://images.unsplash.com/photo-1551782450-17144efb9c50?w=600',
    'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600',
  ],
  menu: {
    Tacos: [
      { name: 'Carne Asada Taco', desc: 'Grilled steak, onion, cilantro, salsa verde', price: 4.25 },
      { name: 'Al Pastor Taco', desc: 'Marinated pork, pineapple, fresh cilantro', price: 4.00 },
      { name: 'Baja Fish Taco', desc: 'Crispy fried fish, slaw, chipotle crema', price: 4.75 },
      { name: 'Veggie Taco', desc: 'Grilled peppers, black beans, queso fresco', price: 3.75 },
    ],
    Burritos: [
      { name: 'Classic Burrito', desc: 'Steak, rice, beans, cheese, pico de gallo', price: 10.50 },
      { name: 'Breakfast Burrito', desc: 'Eggs, chorizo, potatoes, cheese, salsa roja', price: 9.00 },
      { name: 'Veggie Burrito', desc: 'Grilled veggies, rice, black beans, guac', price: 9.50 },
    ],
    Bowls: [
      { name: 'Carnitas Bowl', desc: 'Slow-braised pork, rice, beans, slaw, crema', price: 11.50 },
      { name: 'Chicken Tinga Bowl', desc: 'Smoky shredded chicken, rice, pico, queso', price: 11.00 },
      { name: 'Power Bowl', desc: 'Grilled chicken, quinoa, greens, avocado', price: 12.00 },
    ],
    Drinks: [
      { name: 'Horchata', desc: 'House-made rice & cinnamon drink', price: 3.50 },
      { name: 'Jamaica Agua Fresca', desc: 'Hibiscus, lightly sweetened, served cold', price: 3.50 },
      { name: 'Mexican Coke', desc: 'Cane sugar, glass bottle', price: 3.00 },
      { name: 'Bottled Water', desc: 'Cold and ready to go', price: 2.00 },
    ],
    Sides: [
      { name: 'Street Corn Elote', desc: 'Grilled corn, cotija, chili-lime crema', price: 5.50 },
      { name: 'Chips & Guac', desc: 'Fresh avocado, lime, house-fried chips', price: 6.00 },
      { name: 'Loaded Fries', desc: 'Carne asada, queso, pico, jalapeños', price: 8.50 },
    ],
  },
}
